export const MockBankList = [
  { bin: '422589', name: 'Ngân hàng TNHH MTV CIMB Việt Nam', shortName: 'CIMB' },
  { bin: '458761', name: 'Ngân hàng TNHH MTV HSBC (Việt Nam)', shortName: 'HSBC' },
  { bin: '546034', name: 'Ngân hàng số CAKE by VPBank', shortName: 'CAKE' },
  { bin: '546035', name: 'Ngân hàng số Ubank by VPBank', shortName: 'Ubank' },
  { bin: '668888', name: 'Ngân hàng Đại chúng TNHH Kasikornbank', shortName: 'KBank' },
  { bin: '796500', name: 'DBS Bank Ltd - Chi nhánh TP. Hồ Chí Minh', shortName: 'DBSBank' },
  { bin: '801011', name: 'Ngân hàng Nonghyup - Chi nhánh Hà Nội', shortName: 'Nonghyup' },
  { bin: '970400', name: 'Ngân hàng TMCP Sài Gòn Công Thương', shortName: 'SaigonBank' },
  { bin: '970403', name: 'Ngân hàng TMCP Sài Gòn Thương Tín', shortName: 'Sacombank' },
  {
    bin: '970405',
    name: 'Ngân hàng Nông nghiệp và Phát triển Nông thôn Việt Nam',
    shortName: 'Agribank',
  },
  { bin: '970406', name: 'Ngân hàng TMCP Đông Á', shortName: 'DongABank' },
  { bin: '970407', name: 'Ngân hàng TMCP Kỹ thương Việt Nam', shortName: 'Techcombank' },
  { bin: '970408', name: 'Ngân hàng Thương mại TNHH MTV Dầu Khí Toàn Cầu', shortName: 'GPBank' },
  { bin: '970409', name: 'Ngân hàng TMCP Bắc Á', shortName: 'BacABank' },
  { bin: '970410', name: 'Ngân hàng Standard Chartered Việt Nam', shortName: 'Standard Chartered' },
  { bin: '970412', name: 'Ngân hàng TMCP Đại Chúng Việt Nam', shortName: 'PVcomBank' },
  { bin: '970414', name: 'Ngân hàng Thương mại TNHH MTV Đại Dương', shortName: 'Oceanbank' },
  { bin: '970415', name: 'Ngân hàng TMCP Công thương Việt Nam', shortName: 'VietinBank' },
  { bin: '970416', name: 'Ngân hàng TMCP Á Châu', shortName: 'ACB' },
  { bin: '970418', name: 'Ngân hàng TMCP Đầu tư và Phát triển Việt Nam', shortName: 'BIDV' },
  { bin: '970419', name: 'Ngân hàng TMCP Quốc Dân', shortName: 'NCB' },
  { bin: '970421', name: 'Ngân hàng Liên doanh Việt - Nga', shortName: 'VRB' },
  { bin: '970422', name: 'Ngân hàng TMCP Quân đội', shortName: 'MBBank' },
  { bin: '970423', name: 'Ngân hàng TMCP Tiên Phong', shortName: 'TPBank' },
  { bin: '970424', name: 'Ngân hàng TNHH MTV Shinhan Việt Nam', shortName: 'ShinhanBank' },
  { bin: '970425', name: 'Ngân hàng TMCP An Bình', shortName: 'ABBANK' },
  { bin: '970426', name: 'Ngân hàng TMCP Hàng Hải', shortName: 'MSB' },
  { bin: '970427', name: 'Ngân hàng TMCP Việt Á', shortName: 'VietABank' },
  { bin: '970428', name: 'Ngân hàng TMCP Nam Á', shortName: 'NamABank' },
  { bin: '970429', name: 'Ngân hàng TMCP Sài Gòn', shortName: 'SCB' },
  { bin: '970430', name: 'Ngân hàng TMCP Xăng dầu Petrolimex', shortName: 'PGBank' },
  { bin: '970431', name: 'Ngân hàng TMCP Xuất Nhập khẩu Việt Nam', shortName: 'Eximbank' },
  { bin: '970432', name: 'Ngân hàng TMCP Việt Nam Thịnh Vượng', shortName: 'VPBank' },
  { bin: '970433', name: 'Ngân hàng TMCP Việt Nam Thương Tín', shortName: 'VietBank' },
  { bin: '970434', name: 'Ngân hàng TNHH Indovina', shortName: 'IndovinaBank' },
  { bin: '970436', name: 'Ngân hàng TMCP Ngoại Thương Việt Nam', shortName: 'Vietcombank' },
  { bin: '970437', name: 'Ngân hàng TMCP PT Thành phố Hồ Chí Minh', shortName: 'HDBank' },
  { bin: '970438', name: 'Ngân hàng TMCP Bảo Việt', shortName: 'BaoVietBank' },
  { bin: '970439', name: 'Ngân hàng TNHH MTV Public Việt Nam', shortName: 'PublicBank' },
  { bin: '970440', name: 'Ngân hàng TMCP Đông Nam Á', shortName: 'SeABank' },
  { bin: '970441', name: 'Ngân hàng TMCP Quốc tế Việt Nam', shortName: 'VIB' },
  { bin: '970442', name: 'Ngân hàng TNHH MTV Hong Leong Việt Nam', shortName: 'HongLeong' },
  { bin: '970443', name: 'Ngân hàng TMCP Sài Gòn - Hà Nội', shortName: 'SHB' },
  { bin: '970444', name: 'Ngân hàng TM TNHH MTV Xây dựng Việt Nam', shortName: 'CBBank' },
  { bin: '970446', name: 'Ngân hàng Hợp tác xã Việt Nam', shortName: 'COOPBANK' },
  { bin: '970448', name: 'Ngân hàng TMCP Phương Đông', shortName: 'OCB' },
  { bin: '970449', name: 'Ngân hàng TMCP Bưu Điện Liên Việt', shortName: 'LienVietPostBank' },
  { bin: '970452', name: 'Ngân hàng TMCP Kiên Long', shortName: 'KienLongBank' },
  { bin: '970454', name: 'Ngân hàng TMCP Bản Việt', shortName: 'VietCapitalBank' },
];
